version: 2.1

orbs:
  go: gotest/tools@0.0.9

workflows:
  ci:
    jobs:
      - go/lint
      - test-golang-1-9:
          name: test-golang-1.9
      - test-golang-1-10:
          name: test-golang-1.10
      - go/test:
          name: test-golang-1.11
          executor:
            name: go/golang
            tag:  1.11-alpine
      - go/test:
          name: test-golang-1.12
          executor:
            name: go/golang
            tag:  1.12-alpine
          codecov-upload: true

commands:
  install-deps:
    description: Install dep and dependencies
    steps:
      - run:
          name: Install dep
          command: |
            command -v dep && exit
            wget -O- -q https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
      - run:
          name: Install dependencies
          command: dep ensure

jobs:

  test-golang-1-9:
    executor:
      name: go/golang
      tag: 1.9-alpine
    working_directory: /go/src/gotest.tools
    steps:
      - go/install: {package: git}
      - go/install-ssh
      - checkout
      - install-deps
      - run:
          name: "Unit Test GO 1.9"
          command: |
            go test -v $(go list ./... | grep -v '/vendor/')

  test-golang-1-10:
    executor:
      name: go/golang
      tag: 1.10-alpine
    working_directory: /go/src/gotest.tools
    steps:
      - go/install: {package: git}
      - go/install-ssh
      - checkout
      - go/install-gotestsum
      - install-deps
      - run:
          name: go test
          environment:
            GOTESTSUM_JUNITFILE: /tmp/test-reports/unit/junit.xml
          command: |
            mkdir -p /tmp/test-reports/unit
            gotestsum
      - store_test_results:
          path: /tmp/test-reports
