version: 2.1

orbs:
  go: gotest/tools@0.0.13

workflows:
  ci:
    jobs:
      - lint
      - test-golang-1-10:
          name: test-golang-1.10
      - go/test:
          name: test-golang-1.11
          executor:
            name: go/golang
            tag:  1.11-alpine
      - go/test:
          name: test-golang-1.12
          executor:
            name: go/golang
            tag:  1.12-alpine
      - go/test:
          name: test-golang-1.13
          executor:
            name: go/golang
            tag:  1.13-alpine
          codecov-upload: true
      - go/test:
          name: test-golang-1.14
          executor:
            name: go/golang
            tag:  1.14rc1-alpine
      - go/test:
          name: test-windows-go1.12
          executor: windows
          pre-steps:
            - run: |
                git config --global core.autocrlf false
                git config --global core.symlinks true

executors:
  windows:
    machine:
      image: windows-server-2019-vs2019:201908-06
      resource_class: windows.medium
      shell: bash.exe

commands:
  install-deps:
    description: Install dep and dependencies
    steps:
      - run:
          name: Install dep
          command: |
            command -v dep && exit
            wget -O- -q https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
      - run:
          name: Install dependencies
          command: dep ensure

jobs:

  test-golang-1-10:
    executor:
      name: go/golang
      tag: 1.10-alpine
    working_directory: /go/src/gotest.tools/v3
    steps:
      - go/install: {package: git}
      - go/install-ssh
      - checkout
      - go/install-gotestsum
      - install-deps
      - run:
          name: go test
          environment:
            GOTESTSUM_JUNITFILE: /tmp/test-reports/unit/junit.xml
          command: |
            mkdir -p /tmp/test-reports/unit
            gotestsum
      - store_test_results:
          path: /tmp/test-reports

  lint:
    executor: go/golang
    steps:
    - checkout
    - go/install-golangci-lint:
        prefix: v2
        version: 1.21.0
    - run:
        name: Lint
        command: |
          golangci-lint run -v --concurrency 2
